Vagrant.configure("2") do |config|             

  config.vm.define "ns2" do |ns2|

    ns2.vm.box = "ubuntu/focal64"

    ns2.vm.hostname="ns2"

    ns2.vm.network "forwarded_port", guest: 22, host: 10004, host_ip: "127.0.0.1"

    ns2.vm.network "private_network", ip: "192.168.1.1",virtualbox__intnet: true, virtualbox__intnet:"intneta"

    ns2.vm.provider :virtualbox do |vb|

                          # Custom CPU & Memory

                          vb.customize ["modifyvm", :id, "--memory", "4096"]

                          vb.customize ["modifyvm", :id, "--cpus", "2"]

    end

    ns2.vm.provision :shell, run: "always", path: "scripts/ns2.sh"

  end

  config.vm.define "ns1" do |ns1|

    ns1.vm.box = "ubuntu/focal64"

    ns1.vm.hostname="ns1"

    ns1.vm.network "forwarded_port", guest: 22, host: 10005, host_ip: "127.0.0.1"


    ns1.vm.network "private_network", ip: "192.168.1.2", virtualbox__intnet: true, virtualbox__intnet:"intneta"

    ns1.vm.provider :virtualbox do |vb|

                          # Custom CPU & Memory

                          vb.customize ["modifyvm", :id, "--memory", "4096"]

                          vb.customize ["modifyvm", :id, "--cpus", "2"]

    end

    ns1.vm.provision :shell, run: "always", path: "scripts/ns1.sh"

    # sudo ip r a 192.168.2.2 via 192.168.1.1 dev enp0s8


  end

  config.vm.define "ns3" do |ns3|

    ns3.vm.box = "ubuntu/focal64"

    ns3.vm.hostname="ns3"

    ns3.vm.network "forwarded_port", guest: 22, host: 10006, host_ip: "127.0.0.1"

    ns3.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: true, virtualbox__intnet:"intneta"

    ns3.vm.provider :virtualbox do |vb|

                          # Custom CPU & Memory

                          vb.customize ["modifyvm", :id, "--memory", "4096"]

                          vb.customize ["modifyvm", :id, "--cpus", "2"]

    end

    ns3.vm.provision :shell, run: "always", path: "scripts/ns3.sh"

    # sudo ip r a 192.168.1.2 via 192.168.2.1 dev enp0s8

  end

  config.vm.define "client" do |client|

    client.vm.box = "ubuntu/focal64"

    client.vm.hostname="client"

    client.vm.network "forwarded_port", guest: 22, host: 10007, host_ip: "127.0.0.1"

    client.vm.network "private_network", ip: "192.168.1.4", virtualbox__intnet: true, virtualbox__intnet:"intneta"

    client.vm.provider :virtualbox do |vb|

                          # Custom CPU & Memory

                          vb.customize ["modifyvm", :id, "--memory", "4096"]

                          vb.customize ["modifyvm", :id, "--cpus", "2"]

    end

    client.vm.provision :shell, run: "always", path: "scripts/client.sh"

  end

end