Vagrant.configure("2") do |config|      
  
  config.vm.define "lab1" do |lab1|

    lab1.vm.box = "ubuntu/focal64"

    lab1.vm.hostname="lab1"

    lab1.vm.network "forwarded_port", guest: 22, host: 10004, host_ip: "127.0.0.1"

    lab1.vm.network "private_network", ip: "192.168.1.1",virtualbox__intnet: true, virtualbox__intnet:"intneta"

    lab1.vm.provider :virtualbox do |vb|

                          # Custom CPU & Memory

                          vb.customize ["modifyvm", :id, "--memory", "4096"]

                          vb.customize ["modifyvm", :id, "--cpus", "2"]

    end

    lab1.vm.provision "shell", inline: <<-SHELL

    sudo echo "192.168.1.1 lab1" | sudo tee -a /etc/hosts

    sudo echo "192.168.1.2 lab2" | sudo tee -a /etc/hosts


    # sudo apt install net-tools

    # sudo apt-get install traceroute

    # sudo apt upgrage -y

    # sudo apt update


SHELL

  end

  config.vm.define "lab2" do |lab2|

    lab2.vm.box = "ubuntu/focal64"

    lab2.vm.hostname="lab2"

    lab2.vm.network "forwarded_port", guest: 22, host: 10005, host_ip: "127.0.0.1"


    lab2.vm.network "private_network", ip: "192.168.1.2", virtualbox__intnet: true, virtualbox__intnet:"intneta"

    lab2.vm.provider :virtualbox do |vb|

                          # Custom CPU & Memory

                          vb.customize ["modifyvm", :id, "--memory", "4096"]

                          vb.customize ["modifyvm", :id, "--cpus", "2"]

    end

    lab2.vm.provision "shell", inline: <<-SHELL

    sudo echo "192.168.1.1 lab1" | sudo tee -a /etc/hosts

    sudo echo "192.168.1.2 lab2" | sudo tee -a /etc/hosts

    # sudo apt install net-tools

    # sudo apt-get install traceroute

    # sudo apt upgrage -y

    # sudo apt update

    # sudo ip r a 192.168.2.2 via 192.168.1.1 dev enp0s8

SHELL

  end

  config.vm.provision "shell", inline: <<-SHELL

  sudo apt install net-tools

SHELL

end