Vagrant.configure("2") do |config|             

  config.vm.define "lab1" do |lab1|

    lab1.vm.box = "ubuntu/focal64"

    lab1.vm.hostname="lab1"

    lab1.vm.network "forwarded_port", guest: 22, host: 10013, host_ip: "127.0.0.1"

    lab1.vm.network "private_network", ip: "192.168.1.1",virtualbox__intnet: true, virtualbox__intnet:"intneta"

    (0..3).each do |i|
      lab1.vm.disk :disk, size: "5GB", name: "disk-#{i}"
    end

    lab1.vm.provider :virtualbox do |vb|

              # Custom CPU & Memory

              vb.customize ["modifyvm", :id, "--memory", "2048"]

              vb.customize ["modifyvm", :id, "--cpus", "1"]

    end

    lab1.vm.provision :shell, run: "always", path: "scripts/lab1.sh"

  end

  config.vm.define "lab2" do |lab2|

    lab2.vm.box = "ubuntu/focal64"

    lab2.vm.hostname="lab2"

    lab2.vm.network "forwarded_port", guest: 22, host: 10014, host_ip: "127.0.0.1"

    lab2.vm.network "private_network", ip: "192.168.1.2", virtualbox__intnet: true, virtualbox__intnet:"intneta"

    lab2.vm.provider :virtualbox do |vb|

                          # Custom CPU & Memory

                          vb.customize ["modifyvm", :id, "--memory", "2048"]

                          vb.customize ["modifyvm", :id, "--cpus", "1"]

    end

    lab2.vm.provision :shell, run: "always", path: "scripts/lab2.sh"

    # sudo ip r a 192.168.2.2 via 192.168.1.1 dev enp0s8
  end
  config.group.groups = {
    "nfs" => [
      "lab1",
      "lab2"
    ],
  }

end